///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ReturnMyLeaveListleave {
/*
{
  "id": 36,
  "staff_id": 1740821001,
  "tanggal": "2021-12-09",
  "ket": "Hehe",
  "status": 0,
  "tipe": "Haid",
  "mulai": "2021-12-09",
  "akhir": "2021-12-09",
  "jam_mulai": "21:45:00",
  "jam_akhir": "21:45:00",
  "branch_id": 1,
  "instansi_id": 3
} 
*/

  int? id;
  String? staffId;
  String? tanggal;
  String? ket;
  int? status;
  String? tipe;
  String? mulai;
  String? akhir;
  String? jamMulai;
  String? jamAkhir;
  int? branchId;
  int? instansiId;

  ReturnMyLeaveListleave({
    this.id,
    this.staffId,
    this.tanggal,
    this.ket,
    this.status,
    this.tipe,
    this.mulai,
    this.akhir,
    this.jamMulai,
    this.jamAkhir,
    this.branchId,
    this.instansiId,
  });
  ReturnMyLeaveListleave.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    staffId = json['staff_id']?.toString();
    tanggal = json['tanggal']?.toString();
    ket = json['ket']?.toString();
    status = json['status']?.toInt();
    tipe = json['tipe']?.toString();
    mulai = json['mulai']?.toString();
    akhir = json['akhir']?.toString();
    jamMulai = json['jam_mulai']?.toString();
    jamAkhir = json['jam_akhir']?.toString();
    branchId = json['branch_id']?.toInt();
    instansiId = json['instansi_id']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['staff_id'] = staffId;
    data['tanggal'] = tanggal;
    data['ket'] = ket;
    data['status'] = status;
    data['tipe'] = tipe;
    data['mulai'] = mulai;
    data['akhir'] = akhir;
    data['jam_mulai'] = jamMulai;
    data['jam_akhir'] = jamAkhir;
    data['branch_id'] = branchId;
    data['instansi_id'] = instansiId;
    return data;
  }
}

class ReturnMyLeave {
/*
{
  "status_json": true,
  "remarks": "Berhasil",
  "listleave": [
    {
      "id": 36,
      "staff_id": 1740821001,
      "tanggal": "2021-12-09",
      "ket": "Hehe",
      "status": 0,
      "tipe": "Haid",
      "mulai": "2021-12-09",
      "akhir": "2021-12-09",
      "jam_mulai": "21:45:00",
      "jam_akhir": "21:45:00",
      "branch_id": 1,
      "instansi_id": 3
    }
  ]
} 
*/

  bool? statusJson;
  String? remarks;
  late List<ReturnMyLeaveListleave> listleave;

  ReturnMyLeave({
    this.statusJson,
    this.remarks,
    required this.listleave,
  });
  ReturnMyLeave.fromJson(Map<String, dynamic> json) {
    statusJson = json['status_json'];
    remarks = json['remarks']?.toString();
    if (json['listleave'] != null) {
      final v = json['listleave'];
      final arr0 = <ReturnMyLeaveListleave>[];
      v.forEach((v) {
        arr0.add(ReturnMyLeaveListleave.fromJson(v));
      });
      listleave = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status_json'] = statusJson;
    data['remarks'] = remarks;
    // ignore: unnecessary_null_comparison
    if (listleave != null) {
      final v = listleave;
      final arr0 = [];
      v.forEach((v) {
        arr0.add(v.toJson());
      });
      data['listleave'] = arr0;
    }
    return data;
  }
}
