///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ReturnDocumentTypeListDocument {
/*
{
  "id": 36,
  "nama": "KTP"
} 
*/

  int? id;
  String? nama;

  ReturnDocumentTypeListDocument({
    this.id,
    this.nama,
  });
  ReturnDocumentTypeListDocument.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    nama = json['nama']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['nama'] = nama;
    return data;
  }
}

class ReturnDocumentType {
/*
{
  "status_json": true,
  "remarks": "Berhasil",
  "list_document": [
    {
      "id": 36,
      "nama": "KTP"
    }
  ]
} 
*/

  bool? statusJson;
  String? remarks;
  List<ReturnDocumentTypeListDocument?>? listDocument;

  ReturnDocumentType({
    this.statusJson,
    this.remarks,
    this.listDocument,
  });
  ReturnDocumentType.fromJson(Map<String, dynamic> json) {
    statusJson = json['status_json'];
    remarks = json['remarks']?.toString();
    if (json['list_document'] != null) {
      final v = json['list_document'];
      final arr0 = <ReturnDocumentTypeListDocument>[];
      v.forEach((v) {
        arr0.add(ReturnDocumentTypeListDocument.fromJson(v));
      });
      listDocument = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status_json'] = statusJson;
    data['remarks'] = remarks;
    if (listDocument != null) {
      final v = listDocument;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['list_document'] = arr0;
    }
    return data;
  }
}
