///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class PostAbsen {
/*
{
  "tipe_absen": "1",
  "datang_pulang": "out",
  "wfh_wfo": "wfh",
  "tanggal_absen": "2021-08-09",
  "jam_absen": "02:54:02",
  "lokasi": "Jalan PU 35, Cimuning, Kecamatan Mustika Jaya, Kota Bekasi, Jawa Barat 17154, Indonesia",
  "latitude": "-6.34",
  "longitude": "107.020889",
  "keterangan": null
} 
*/

  String? tipe_absen;
  String? datang_pulang;
  String? wfh_wfo;
  String? tanggal_absen;
  String? jam_absen;
  String? lokasi;
  String? latitude;
  String? longitude;
  String? keterangan;
  String? timezone;
  String? timezoneoffset;
  String? deviceid;
  String? version;
  String? foto;
  dynamic id_shift;
  dynamic jam_absen_wajib;
  int? cabang_id;
  int? section_id;

  PostAbsen({
    this.foto,
    this.tipe_absen,
    this.datang_pulang,
    this.wfh_wfo,
    this.tanggal_absen,
    this.jam_absen,
    this.lokasi,
    this.latitude,
    this.longitude,
    this.keterangan,
    this.cabang_id,
    this.section_id,
    this.timezone,
    this.deviceid,
    this.version,
    this.id_shift,
    this.jam_absen_wajib,
  });
  PostAbsen.fromJson(Map<String, dynamic> json) {
    tipe_absen = json["tipe_absen"]?.toString();
    id_shift = json["id_shift"]?.toString();
    jam_absen_wajib = json["jam_absen_wajib"]?.toString();
    datang_pulang = json["datang_pulang"]?.toString();
    wfh_wfo = json["wfh_wfo"]?.toString();
    tanggal_absen = json["tanggal_absen"]?.toString();
    jam_absen = json["jam_absen"]?.toString();
    lokasi = json["lokasi"]?.toString();
    latitude = json["latitude"]?.toString();
    longitude = json["longitude"]?.toString();
    keterangan = json["keterangan"]?.toString();
    cabang_id = json["cabang_id"]?.toInt();
    section_id = json["section_id"]?.toInt();
    timezone = json["timezone"]?.toString();
    timezoneoffset = json["timezoneoffset"]?.toString();
    deviceid = json["deviceid"]?.toString();
    version = json["version"]?.toString();
    foto = json["foto"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["tipe_absen"] = tipe_absen;
    data["id_shift"] = id_shift;
    data["jam_absen_wajib"] = jam_absen_wajib;
    data["datang_pulang"] = datang_pulang;
    data["wfh_wfo"] = wfh_wfo;
    data["tanggal_absen"] = tanggal_absen;
    data["jam_absen"] = jam_absen;
    data["lokasi"] = lokasi;
    data["latitude"] = latitude;
    data["longitude"] = longitude;
    data["keterangan"] = keterangan;
    data["cabang_id"] = cabang_id;
    data["section_id"] = section_id;
    data["timezone"] = timezone;
    data["timezoneoffset"] = timezoneoffset;
    data["deviceid"] = deviceid;
    data["version"] = version;
    data["foto"] = foto;

    return data;
  }
}
