///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ReturnCheck {
/*
{
  "status_json": false,
  "remarks": "Password salah"
} 
*/

  bool? statusJson;
  String? remarks;

  ReturnCheck({
    this.statusJson,
    this.remarks,
  });
  ReturnCheck.fromJson(Map<String, dynamic> json) {
    statusJson = json["status_json"];
    remarks = json["remarks"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["status_json"] = statusJson;
    data["remarks"] = remarks;
    return data;
  }
}
