///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ReturnFaceData {
/*
{
  "status": false,
  "message": "Cannot read property 'descriptor' of undefined"
} 
*/

  bool? status;
  String? message;

  ReturnFaceData({
    this.status,
    this.message,
  });
  ReturnFaceData.fromJson(Map<String, dynamic> json) {
    status = json["status"];
    message = json["message"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["status"] = status;
    data["message"] = message;
    return data;
  }
}
