///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ReturnMyPersonalProfilPersonalProfil {
/*
{
  "nik": "2225",
  "first_name": "Fft",
  "phone": "5585",
  "address": "Fttf",
  "gender": "Fftf",
  "birth_place": "Fttf",
  "birth_day": "2021-12-29",
  "blood": "Ftft"
} 
*/

  String? nik;
  String? firstName;
  String? phone;
  String? address;
  String? gender;
  String? birthPlace;
  String? birthDay;
  String? blood;

  ReturnMyPersonalProfilPersonalProfil({
    this.nik,
    this.firstName,
    this.phone,
    this.address,
    this.gender,
    this.birthPlace,
    this.birthDay,
    this.blood,
  });
  ReturnMyPersonalProfilPersonalProfil.fromJson(Map<String, dynamic> json) {
    nik = json['nik']?.toString();
    firstName = json['first_name']?.toString();
    phone = json['phone']?.toString();
    address = json['address']?.toString();
    gender = json['gender']?.toString();
    birthPlace = json['birth_place']?.toString();
    birthDay = json['birth_day']?.toString();
    blood = json['blood']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['nik'] = nik;
    data['first_name'] = firstName;
    data['phone'] = phone;
    data['address'] = address;
    data['gender'] = gender;
    data['birth_place'] = birthPlace;
    data['birth_day'] = birthDay;
    data['blood'] = blood;
    return data;
  }
}

class ReturnMyPersonalProfil {
/*
{
  "status_json": true,
  "remarks": "Successfully get_personal_info_get",
  "personal_profil": {
    "nik": "2225",
    "first_name": "Fft",
    "phone": "5585",
    "address": "Fttf",
    "gender": "Fftf",
    "birth_place": "Fttf",
    "birth_day": "2021-12-29",
    "blood": "Ftft"
  }
} 
*/

  bool? statusJson;
  String? remarks;
  ReturnMyPersonalProfilPersonalProfil? personalProfil;

  ReturnMyPersonalProfil({
    this.statusJson,
    this.remarks,
    this.personalProfil,
  });
  ReturnMyPersonalProfil.fromJson(Map<String, dynamic> json) {
    statusJson = json['status_json'];
    remarks = json['remarks']?.toString();
    personalProfil = (json['personal_profil'] != null)
        ? ReturnMyPersonalProfilPersonalProfil.fromJson(json['personal_profil'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status_json'] = statusJson;
    data['remarks'] = remarks;
    if (personalProfil != null) {
      data['personal_profil'] = personalProfil!.toJson();
    }
    return data;
  }
}
