///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class PostPersonalProfil {
/*
{
  "nik": "12121212",
  "first_name": "FARID RAMADHAN",
  "phone": "081290223582",
  "address": "jl mayang raya",
  "gender": "1",
  "birth_place": "jakartasssss",
  "birth_day": "2021-08-09",
  "blood": "0"
} 
*/

  String? nik;
  String? firstName;
  String? phone;
  String? address;
  String? gender;
  String? birthPlace;
  String? birthDay;
  String? blood;

  PostPersonalProfil({
    this.nik,
    this.firstName,
    this.phone,
    this.address,
    this.gender,
    this.birthPlace,
    this.birthDay,
    this.blood,
  });
  PostPersonalProfil.fromJson(Map<String, dynamic> json) {
    nik = json['nik']?.toString();
    firstName = json['first_name']?.toString();
    phone = json['phone']?.toString();
    address = json['address']?.toString();
    gender = json['gender']?.toString();
    birthPlace = json['birth_place']?.toString();
    birthDay = json['birth_day']?.toString();
    blood = json['blood']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['nik'] = nik;
    data['first_name'] = firstName;
    data['phone'] = phone;
    data['address'] = address;
    data['gender'] = gender;
    data['birth_place'] = birthPlace;
    data['birth_day'] = birthDay;
    data['blood'] = blood;
    return data;
  }
}
