///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ReturnLeaveTypeLeaveType {
/*
{
  "id": 3,
  "leavetype": "Sakit",
  "description": "-",
  "branch_id": 1,
  "instansi_id": 3
} 
*/

  int? id;
  String? leavetype;
  String? description;
  int? branchId;
  int? instansiId;

  ReturnLeaveTypeLeaveType({
    this.id,
    this.leavetype,
    this.description,
    this.branchId,
    this.instansiId,
  });
  ReturnLeaveTypeLeaveType.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    leavetype = json['leavetype']?.toString();
    description = json['description']?.toString();
    branchId = json['branch_id']?.toInt();
    instansiId = json['instansi_id']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['leavetype'] = leavetype;
    data['description'] = description;
    data['branch_id'] = branchId;
    data['instansi_id'] = instansiId;
    return data;
  }
}

class ReturnLeaveType {
/*
{
  "status_json": true,
  "remarks": "Berhasil",
  "leaveType": [
    {
      "id": 3,
      "leavetype": "Sakit",
      "description": "-",
      "branch_id": 1,
      "instansi_id": 3
    }
  ]
} 
*/

  bool? statusJson;
  String? remarks;
  List<ReturnLeaveTypeLeaveType?>? leaveType;

  ReturnLeaveType({
    this.statusJson,
    this.remarks,
    this.leaveType,
  });
  ReturnLeaveType.fromJson(Map<String, dynamic> json) {
    statusJson = json['status_json'];
    remarks = json['remarks']?.toString();
    if (json['leaveType'] != null) {
      final v = json['leaveType'];
      final arr0 = <ReturnLeaveTypeLeaveType>[];
      v.forEach((v) {
        arr0.add(ReturnLeaveTypeLeaveType.fromJson(v));
      });
      leaveType = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status_json'] = statusJson;
    data['remarks'] = remarks;
    if (leaveType != null) {
      final v = leaveType;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['leaveType'] = arr0;
    }
    return data;
  }
}
