///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class BankAccountBankAccount {
/*
{
  "bank_name": "FARID RAMADHAN",
  "bank_accountno": "121212"
} 
*/

  String? bankName;
  String? bankAccountno;

  BankAccountBankAccount({
    this.bankName,
    this.bankAccountno,
  });
  BankAccountBankAccount.fromJson(Map<String, dynamic> json) {
    bankName = json['bank_name']?.toString();
    bankAccountno = json['bank_accountno']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['bank_name'] = bankName;
    data['bank_accountno'] = bankAccountno;
    return data;
  }
}

class BankAccount {
/*
{
  "status_json": true,
  "remarks": "Successfully get_bank_account_get",
  "bank_account": {
    "bank_name": "FARID RAMADHAN",
    "bank_accountno": "121212"
  }
} 
*/

  bool? statusJson;
  String? remarks;
  BankAccountBankAccount? bankAccount;

  BankAccount({
    this.statusJson,
    this.remarks,
    this.bankAccount,
  });
  BankAccount.fromJson(Map<String, dynamic> json) {
    statusJson = json['status_json'];
    remarks = json['remarks']?.toString();
    bankAccount = (json['bank_account'] != null)
        ? BankAccountBankAccount.fromJson(json['bank_account'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status_json'] = statusJson;
    data['remarks'] = remarks;
    if (bankAccount != null) {
      data['bank_account'] = bankAccount!.toJson();
    }
    return data;
  }
}
