///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class PostLogin {
/*
{
  "username": "satrio@gmail.com",
  "password": "123456"
} 
*/

  String? username;
  String? password;

  PostLogin({
    this.username,
    this.password,
  });
  PostLogin.fromJson(Map<String, dynamic> json) {
    username = json["username"]?.toString();
    password = json["password"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["username"] = username;
    data["password"] = password;
    return data;
  }
}

class PostDeviceId {
  String? version;
  String? ostype;
  String? deviceId;
  String? deviceDesc;

  PostDeviceId({
    this.version,
    this.ostype,
    this.deviceId,
    this.deviceDesc,
  });
  PostDeviceId.fromJson(Map<String, dynamic> json) {
    ostype = json["ostype"]?.toString();
    version = json["version"]?.toString();
    deviceId = json["deviceId"]?.toString();
    deviceDesc = json["deviceDesc"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["ostype"] = ostype;
    data["version"] = version;
    data["deviceId"] = deviceId;
    data["deviceDesc"] = deviceDesc;
    return data;
  }
}
