///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ReturnStaffShiftListshift {
/*
{
  "jam_dari": "00:30:00",
  "jam_sampai": "15:00:00"
} 
*/

  String? jamDari;
  String? jamSampai;

  ReturnStaffShiftListshift({
    this.jamDari,
    this.jamSampai,
  });
  ReturnStaffShiftListshift.fromJson(Map<String, dynamic> json) {
    jamDari = json["jam_dari"]?.toString();
    jamSampai = json["jam_sampai"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["jam_dari"] = jamDari;
    data["jam_sampai"] = jamSampai;
    return data;
  }
}

class ReturnStaffShift {
/*
{
  "status_json": true,
  "remarks": "Berhasil",
  "dateNow": "2021-10-18",
  "hari": "Senin",
  "listshift": {
    "jam_dari": "00:30:00",
    "jam_sampai": "15:00:00"
  }
} 
*/

  bool? statusJson;
  String? remarks;
  String? dateNow;
  String? hari;
  ReturnStaffShiftListshift? listshift;

  ReturnStaffShift({
    this.statusJson,
    this.remarks,
    this.dateNow,
    this.hari,
    this.listshift,
  });
  ReturnStaffShift.fromJson(Map<String, dynamic> json) {
    statusJson = json["status_json"];
    remarks = json["remarks"]?.toString();
    dateNow = json["dateNow"]?.toString();
    hari = json["hari"]?.toString();
    listshift = (json["listshift"] != null) ? ReturnStaffShiftListshift.fromJson(json["listshift"]) : null;
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["status_json"] = statusJson;
    data["remarks"] = remarks;
    data["dateNow"] = dateNow;
    data["hari"] = hari;
    if (listshift != null) {
      data["listshift"] = listshift!.toJson();
    }
    return data;
  }
}
